
import type { Language } from './types';

export const translations: Record<Language, Record<string, any>> = {
  en: {
    title: "Kid's AI World",
    storyTime: 'Story Time',
    mnemonics: 'Mnemonics',
    onlineAdventure: 'Online Adventure',
    myVocab: 'My Vocab',
    studyBuddy: 'Study Buddy',
    healthAdviser: 'My AI Health Adviser',
    storyIntro: 'Answer 5 questions about your interests, and I will tell you a magical audio story with pictures!',
    questions: [
        "What is your favorite animal?",
        "What is your favorite color?",
        "What superpower would you like to have?",
        "Where would you like to travel: to a jungle, to space, or under the sea?",
        "Who is your best friend?"
    ],
    generateStory: 'Generate Story',
    generating: 'Generating your magical story... This might take a minute!',
    generatingStory: 'Writing the story...',
    generatingImages: 'Drawing the pictures...',
    generatingAudio: 'Recording the audio...',
    storyError: 'Oops! I couldn\'t create a story right now. Please try again.',
    mnemonicsIntro: 'Enter 3 to 10 words you want to remember, and I will create a fun picture to help you!',
    addWord: 'Add Word',
    enterWord: 'Enter a word',
    generateImage: 'Generate Image',
    words: 'Words',
    mnemonicsError: 'Couldn\'t create an image. Please check your words and try again.',
    adventureIntro: 'Upload your photo, choose a theme, and go on an amazing adventure!',
    uploadImage: 'Upload Your Photo',
    chooseTheme: 'Choose your adventure:',
    themes: [
        { value: 'a brave knight in a fantasy kingdom', label: 'Brave Knight' },
        { value: 'an astronaut exploring a new planet', label: 'Space Explorer' },
        { value: 'a superhero flying over a big city', label: 'Superhero' },
        { value: 'a character from the cartoon "Paw Patrol"', label: 'Paw Patrol Character'},
        { value: 'a wizard in a magical school', label: 'Wizard'}
    ],
    yourAdventure: 'Your Adventure!',
    adventureError: 'Could not create your adventure image. Please try another photo or theme.',
    vocabEmpty: "You haven't saved any words yet. Go to Mnemonics to create some magic!",
    delete: 'Delete',
    studyIntro: 'Ask me anything about your school subjects! I can help with Science, Math, History, and more.',
    selectSubject: 'Select a Subject',
    subjects: [
      { value: 'cs', label: 'Computer Science' },
      { value: 'medicine', label: 'Medicine & Biology' },
      { value: 'history', label: 'History' },
      { value: 'math', label: 'Math & Geometry' },
      { value: 'physics', label: 'Physics' },
      { value: 'writing', label: 'Literature & Writing' },
      { value: 'geography', label: 'Geography' }
    ],
    enterQuestion: 'Type your question here...',
    askQuestion: 'Ask Study Buddy',
    studyError: 'I couldn\'t find an answer right now. Try asking differently!',
    generatingAnswer: 'Thinking and drawing...',
    healthIntro: 'Get expert advice on nutrition, sports, diseases, and healthy living with 3D visualizations!',
    healthPlaceholder: 'Ask about vitamins, exercises, how the heart works, or flu symptoms...',
    getHealthAdvice: 'Get Health Advice',
    healthError: 'I couldn\'t provide health advice right now. Please try again.',
    generatingHealth: 'Analyzing health data and rendering 3D model...',
  },
  uz: {
    title: "Bolalar AI Dunyosi",
    storyTime: 'Hikoyalar',
    mnemonics: 'Mnemonika',
    onlineAdventure: 'Onlayn Sarguzasht',
    myVocab: 'Mening Lug\'atim',
    studyBuddy: 'Darsdoshingiz',
    healthAdviser: 'AI Sog\'liq Maslahatchim',
    storyIntro: "Qiziqishlaringiz haqida 5 ta savolga javob bering va men sizga rasmlar bilan ajoyib audio ertak aytib beraman!",
    questions: [
        "Sevimli hayvoningiz qaysi?",
        "Sevimli rangingiz qaysi?",
        "Qanday super kuchga ega bo'lishni xohlardingiz?",
        "Qayerga sayohat qilishni xohlaysiz: changalzorga, koinotga yoki dengiz ostiga?",
        "Eng yaqin do'stingiz kim?"
    ],
    generateStory: 'Ertak Yaratish',
    generating: "Sizning sehrli ertagingiz yaratilmoqda... Bu bir daqiqa vaqt olishi mumkin!",
    generatingStory: 'Hikoya yozilmoqda...',
    generatingImages: 'Rasmlar chizilmoqda...',
    generatingAudio: 'Ovoz yozilmoqda...',
    storyError: 'Uzur! Hozir ertak yarata olmadim. Iltimos, qaytadan urining.',
    mnemonicsIntro: "Eslab qolmoqchi bo'lgan 3 tadan 10 tagacha so'z kiriting va men sizga yordam beradigan qiziqarli rasm yarataman!",
    addWord: "So'z qo'shish",
    enterWord: "So'z kiriting",
    generateImage: 'Rasm Yaratish',
    words: 'So\'zlar',
    mnemonicsError: 'Rasmni yaratib bo\'lmadi. Iltimos, so\'zlaringizni tekshiring va qaytadan urining.',
    adventureIntro: "Rasmingizni yuklang, mavzuni tanlang va ajoyib sarguzashtga boring!",
    uploadImage: 'Rasmingizni Yuklang',
    chooseTheme: 'Sarguzashtingizni tanlang:',
    themes: [
        { value: 'fantastik qirollikdagi jasur ritsar', label: 'Jasur Ritsar' },
        { value: 'yangi sayyorani o`rganayotgan astronavt', label: 'Koinot Tadqiqotchisi' },
        { value: 'katta shahar uzra uchayotgan superqahramon', label: 'Superqahramon' },
        { value: '"Paw Patrol" multfilmidagi qahramon', label: 'Paw Patrol Qahramoni'},
        { value: 'sehrli maktabdagi sehrgar', label: 'Sehrgar'}
    ],
    yourAdventure: 'Sizning Sarguzashtingiz!',
    adventureError: 'Sarguzasht rasmingizni yaratib bo\'lmadi. Iltimos, boshqa rasm yoki mavzu bilan qaytadan urining.',
    vocabEmpty: "Hali hech narsa saqlanmadi. Mnemonika bo'limida sehrli rasmlar yarating!",
    delete: "O'chirish",
    studyIntro: 'Darslaringiz bo\'yicha xohlagan savolingizni bering! Fan, matematika, tarix va boshqalarda yordam bera olaman.',
    selectSubject: 'Fanni tanlang',
    subjects: [
      { value: 'cs', label: 'Kompyuter ilmlari' },
      { value: 'medicine', label: 'Tibbiyot va Biologiya' },
      { value: 'history', label: 'Tarix' },
      { value: 'math', label: 'Matematika va Geometriya' },
      { value: 'physics', label: 'Fizika' },
      { value: 'writing', label: 'Adabiyot va Yozuv' },
      { value: 'geography', label: 'Geografiya' }
    ],
    enterQuestion: 'Savolingizni shu yerga yozing...',
    askQuestion: 'Javob olish',
    studyError: 'Hozir javob topa olmadim. Boshqacha so\'rab ko\'ring!',
    generatingAnswer: 'O\'ylayapman va chizayapman...',
    healthIntro: 'Oziqlanish, sport, kasalliklar va sog\'lom turmush tarzi haqida 3D rasmlar bilan maslahat oling!',
    healthPlaceholder: 'Vitaminlar, mashqlar, yurak ishlashi yoki gripp haqida so\'rang...',
    getHealthAdvice: 'Maslahat Olish',
    healthError: 'Hozircha sog\'liq bo\'yicha maslahat bera olmayman. Qaytadan urinib ko\'ring.',
    generatingHealth: 'Ma\'lumotlar tahlil qilinmoqda va 3D model chizilmoqda...',
  },
  ru: {
    title: "Детский Мир ИИ",
    storyTime: 'Сказки',
    mnemonics: 'Мнемоника',
    onlineAdventure: 'Онлайн-приключение',
    myVocab: 'Мой Словарь',
    studyBuddy: 'Умный Помощник',
    healthAdviser: 'ИИ Консультант Здоровья',
    storyIntro: 'Ответьте на 5 вопросов о ваших интересах, и я расскажу вам волшебную аудио-сказку с картинками!',
    questions: [
        "Какое ваше любимое животное?",
        "Какой ваш любимый цвет?",
        "Какой суперсилой вы бы хотели обладать?",
        "Куда бы вы хотели отправиться: в джунгли, в космос или под воду?",
        "Кто ваш лучший друг?"
    ],
    generateStory: 'Создать сказку',
    generating: "Создаю вашу волшебную сказку... Это может занять минуту!",
    generatingStory: 'Пишу историю...',
    generatingImages: 'Рисую картинки...',
    generatingAudio: 'Записываю аудио...',
    storyError: 'Ой! Не удалось создать сказку прямо сейчас. Пожалуйста, попробуйте еще раз.',
    mnemonicsIntro: 'Введите от 3 до 10 слов, которые вы хотите запомнить, и я создам забавную картинку, чтобы помочь вам!',
    addWord: 'Добавить слово',
    enterWord: 'Введите слово',
    generateImage: 'Создать изображение',
    words: 'Слова',
    mnemonicsError: 'Не удалось создать изображение. Пожалуйста, проверьте слова и попробуйте снова.',
    adventureIntro: 'Загрузите свое фото, выберите тему и отправляйтесь в удивительное приключение!',
    uploadImage: 'Загрузите ваше фото',
    chooseTheme: 'Выберите ваше приключение:',
    themes: [
        { value: 'храбрый рыцарь в фэнтезийном королевстве', label: 'Храбрый Рыцарь' },
        { value: 'астронавт, исследующий новую планету', label: 'Исследователь Космоса' },
        { value: 'супергерой, летящий над большим городом', label: 'Супергерой' },
        { value: 'персонаж из мультфильма "Щенячий патруль"', label: 'Герой Щенячьего патруля'},
        { value: 'волшебник в магической школе', label: 'Волшебник'}
    ],
    yourAdventure: 'Ваше приключение!',
    adventureError: 'Не удалось создать ваше изображение. Пожалуйста, попробуйте другое фото или тему.',
    vocabEmpty: "Пока ничего не сохранено. Создайте волшебные картинки в разделе Мнемоника!",
    delete: 'Удалить',
    studyIntro: 'Спроси меня о чем угодно по школьным предметам! Я помогу с наукой, математикой, историей и многим другим.',
    selectSubject: 'Выберите предмет',
    subjects: [
      { value: 'cs', label: 'Информатика' },
      { value: 'medicine', label: 'Медицина и Биология' },
      { value: 'history', label: 'История' },
      { value: 'math', label: 'Математика и Геометрия' },
      { value: 'physics', label: 'Физика' },
      { value: 'writing', label: 'Литература и Письмо' },
      { value: 'geography', label: 'География' }
    ],
    enterQuestion: 'Напишите ваш вопрос здесь...',
    askQuestion: 'Спросить помощника',
    studyError: 'Я не смог найти ответ прямо сейчас. Попробуйте спросить по-другому!',
    generatingAnswer: 'Думаю и рисую...',
    healthIntro: 'Получите советы экспертов по питанию, спорту, болезням и здоровому образу жизни с 3D-визуализацией!',
    healthPlaceholder: 'Спросите о витаминах, упражнениях, работе сердца или гриппе...',
    getHealthAdvice: 'Получить совет',
    healthError: 'Я не смог предоставить совет по здоровью прямо сейчас. Пожалуйста, попробуйте снова.',
    generatingHealth: 'Анализирую данные и создаю 3D-модель...',
  }
};
